/** Generated by scripts/generate_registry.py. */
const registry = [
  {
    "id": "hardware:resistor",
    "label": "Resistor",
    "category": "passive_component",
    "system": "analog",
    "parent": "hardware:passive_components",
    "aliases": [
      "resistance"
    ],
    "attributes": {
      "kind": "passive"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E100",
    "char": "",
    "ligature": ":resistor:",
    "shortcode": ":resistor:",
    "glyph_name": "hardware_resistor",
    "glyph_base": "resistor",
    "svg": "glyphs/mono/resistor.svg",
    "color_svg": "glyphs/color/resistor.svg",
    "iso_svg": "glyphs/iso/resistor.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Resistor"
  },
  {
    "id": "hardware:variable_resistor",
    "label": "Variable resistor",
    "category": "passive_component",
    "system": "analog",
    "parent": "hardware:passive_components",
    "aliases": [
      "rheostat"
    ],
    "attributes": {
      "kind": "passive"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E101",
    "char": "",
    "ligature": ":variable_resistor:",
    "shortcode": ":variable_resistor:",
    "glyph_name": "hardware_variable_resistor",
    "glyph_base": "variable_resistor",
    "svg": "glyphs/mono/variable_resistor.svg",
    "color_svg": "glyphs/color/variable_resistor.svg",
    "iso_svg": "glyphs/iso/variable_resistor.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Variable resistor"
  },
  {
    "id": "hardware:potentiometer",
    "label": "Potentiometer",
    "category": "passive_component",
    "system": "analog",
    "parent": "hardware:passive_components",
    "aliases": [
      "pot"
    ],
    "attributes": {
      "kind": "passive"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E102",
    "char": "",
    "ligature": ":potentiometer:",
    "shortcode": ":potentiometer:",
    "glyph_name": "hardware_potentiometer",
    "glyph_base": "potentiometer",
    "svg": "glyphs/mono/potentiometer.svg",
    "color_svg": "glyphs/color/potentiometer.svg",
    "iso_svg": "glyphs/iso/potentiometer.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Potentiometer"
  },
  {
    "id": "hardware:ceramic_capacitor",
    "label": "Ceramic capacitor",
    "category": "passive_component",
    "system": "analog",
    "parent": "hardware:passive_components",
    "aliases": [
      "MLCC"
    ],
    "attributes": {
      "kind": "capacitor",
      "dielectric": "ceramic"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E103",
    "char": "",
    "ligature": ":ceramic_capacitor:",
    "shortcode": ":ceramic_capacitor:",
    "glyph_name": "hardware_ceramic_capacitor",
    "glyph_base": "ceramic_capacitor",
    "svg": "glyphs/mono/ceramic_capacitor.svg",
    "color_svg": "glyphs/color/ceramic_capacitor.svg",
    "iso_svg": "glyphs/iso/ceramic_capacitor.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Ceramic capacitor"
  },
  {
    "id": "hardware:electrolytic_capacitor",
    "label": "Electrolytic capacitor",
    "category": "passive_component",
    "system": "analog",
    "parent": "hardware:passive_components",
    "aliases": [
      "electrolytic"
    ],
    "attributes": {
      "kind": "capacitor",
      "polarity": "polarized"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E104",
    "char": "",
    "ligature": ":electrolytic_capacitor:",
    "shortcode": ":electrolytic_capacitor:",
    "glyph_name": "hardware_electrolytic_capacitor",
    "glyph_base": "electrolytic_capacitor",
    "svg": "glyphs/mono/electrolytic_capacitor.svg",
    "color_svg": "glyphs/color/electrolytic_capacitor.svg",
    "iso_svg": "glyphs/iso/electrolytic_capacitor.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Electrolytic capacitor"
  },
  {
    "id": "hardware:inductor",
    "label": "Inductor",
    "category": "passive_component",
    "system": "analog",
    "parent": "hardware:passive_components",
    "aliases": [
      "coil"
    ],
    "attributes": {
      "kind": "passive"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E105",
    "char": "",
    "ligature": ":inductor:",
    "shortcode": ":inductor:",
    "glyph_name": "hardware_inductor",
    "glyph_base": "inductor",
    "svg": "glyphs/mono/inductor.svg",
    "color_svg": "glyphs/color/inductor.svg",
    "iso_svg": "glyphs/iso/inductor.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Inductor"
  },
  {
    "id": "hardware:transformer",
    "label": "Transformer",
    "category": "passive_component",
    "system": "power",
    "parent": "hardware:passive_components",
    "aliases": [
      "power transformer"
    ],
    "attributes": {
      "kind": "magnetic"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E106",
    "char": "",
    "ligature": ":transformer:",
    "shortcode": ":transformer:",
    "glyph_name": "hardware_transformer",
    "glyph_base": "transformer",
    "svg": "glyphs/mono/transformer.svg",
    "color_svg": "glyphs/color/transformer.svg",
    "iso_svg": "glyphs/iso/transformer.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Transformer"
  },
  {
    "id": "hardware:fuse",
    "label": "Fuse",
    "category": "passive_component",
    "system": "power",
    "parent": "hardware:passive_components",
    "aliases": [
      "overcurrent fuse"
    ],
    "attributes": {
      "kind": "protection"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E107",
    "char": "",
    "ligature": ":fuse:",
    "shortcode": ":fuse:",
    "glyph_name": "hardware_fuse",
    "glyph_base": "fuse",
    "svg": "glyphs/mono/fuse.svg",
    "color_svg": "glyphs/color/fuse.svg",
    "iso_svg": "glyphs/iso/fuse.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Fuse"
  },
  {
    "id": "hardware:thermistor",
    "label": "Thermistor",
    "category": "passive_component",
    "system": "analog",
    "parent": "hardware:passive_components",
    "aliases": [
      "temperature resistor"
    ],
    "attributes": {
      "kind": "sensor"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E108",
    "char": "",
    "ligature": ":thermistor:",
    "shortcode": ":thermistor:",
    "glyph_name": "hardware_thermistor",
    "glyph_base": "thermistor",
    "svg": "glyphs/mono/thermistor.svg",
    "color_svg": "glyphs/color/thermistor.svg",
    "iso_svg": "glyphs/iso/thermistor.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Thermistor"
  },
  {
    "id": "hardware:diode",
    "label": "Diode",
    "category": "semiconductor",
    "system": "analog",
    "parent": "hardware:semiconductors",
    "aliases": [
      "rectifier diode"
    ],
    "attributes": {
      "kind": "semiconductor"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E109",
    "char": "",
    "ligature": ":diode:",
    "shortcode": ":diode:",
    "glyph_name": "hardware_diode",
    "glyph_base": "diode",
    "svg": "glyphs/mono/diode.svg",
    "color_svg": "glyphs/color/diode.svg",
    "iso_svg": "glyphs/iso/diode.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Diode"
  },
  {
    "id": "hardware:led",
    "label": "Light-emitting diode",
    "category": "semiconductor",
    "system": "optoelectronics",
    "parent": "hardware:semiconductors",
    "aliases": [
      "LED"
    ],
    "attributes": {
      "kind": "diode"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E10A",
    "char": "",
    "ligature": ":led:",
    "shortcode": ":led:",
    "glyph_name": "hardware_led",
    "glyph_base": "led",
    "svg": "glyphs/mono/led.svg",
    "color_svg": "glyphs/color/led.svg",
    "iso_svg": "glyphs/iso/led.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Light-emitting diode"
  },
  {
    "id": "hardware:photodiode",
    "label": "Photodiode",
    "category": "semiconductor",
    "system": "optoelectronics",
    "parent": "hardware:semiconductors",
    "aliases": [
      "light sensor"
    ],
    "attributes": {
      "kind": "diode"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E10B",
    "char": "",
    "ligature": ":photodiode:",
    "shortcode": ":photodiode:",
    "glyph_name": "hardware_photodiode",
    "glyph_base": "photodiode",
    "svg": "glyphs/mono/photodiode.svg",
    "color_svg": "glyphs/color/photodiode.svg",
    "iso_svg": "glyphs/iso/photodiode.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Photodiode"
  },
  {
    "id": "hardware:npn_transistor",
    "label": "NPN transistor",
    "category": "semiconductor",
    "system": "analog",
    "parent": "hardware:semiconductors",
    "aliases": [
      "NPN"
    ],
    "attributes": {
      "kind": "BJT",
      "polarity": "NPN"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E10C",
    "char": "",
    "ligature": ":npn_transistor:",
    "shortcode": ":npn_transistor:",
    "glyph_name": "hardware_npn_transistor",
    "glyph_base": "npn_transistor",
    "svg": "glyphs/mono/npn_transistor.svg",
    "color_svg": "glyphs/color/npn_transistor.svg",
    "iso_svg": "glyphs/iso/npn_transistor.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "NPN transistor"
  },
  {
    "id": "hardware:pnp_transistor",
    "label": "PNP transistor",
    "category": "semiconductor",
    "system": "analog",
    "parent": "hardware:semiconductors",
    "aliases": [
      "PNP"
    ],
    "attributes": {
      "kind": "BJT",
      "polarity": "PNP"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E10D",
    "char": "",
    "ligature": ":pnp_transistor:",
    "shortcode": ":pnp_transistor:",
    "glyph_name": "hardware_pnp_transistor",
    "glyph_base": "pnp_transistor",
    "svg": "glyphs/mono/pnp_transistor.svg",
    "color_svg": "glyphs/color/pnp_transistor.svg",
    "iso_svg": "glyphs/iso/pnp_transistor.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "PNP transistor"
  },
  {
    "id": "hardware:mosfet",
    "label": "MOSFET",
    "category": "semiconductor",
    "system": "power",
    "parent": "hardware:semiconductors",
    "aliases": [
      "MOS transistor"
    ],
    "attributes": {
      "kind": "FET"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E10E",
    "char": "",
    "ligature": ":mosfet:",
    "shortcode": ":mosfet:",
    "glyph_name": "hardware_mosfet",
    "glyph_base": "mosfet",
    "svg": "glyphs/mono/mosfet.svg",
    "color_svg": "glyphs/color/mosfet.svg",
    "iso_svg": "glyphs/iso/mosfet.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "MOSFET"
  },
  {
    "id": "hardware:voltage_regulator",
    "label": "Voltage regulator",
    "category": "semiconductor",
    "system": "power",
    "parent": "hardware:semiconductors",
    "aliases": [
      "regulator"
    ],
    "attributes": {
      "kind": "power"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E10F",
    "char": "",
    "ligature": ":voltage_regulator:",
    "shortcode": ":voltage_regulator:",
    "glyph_name": "hardware_voltage_regulator",
    "glyph_base": "voltage_regulator",
    "svg": "glyphs/mono/voltage_regulator.svg",
    "color_svg": "glyphs/color/voltage_regulator.svg",
    "iso_svg": "glyphs/iso/voltage_regulator.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Voltage regulator"
  },
  {
    "id": "hardware:op_amp",
    "label": "Operational amplifier",
    "category": "semiconductor",
    "system": "analog",
    "parent": "hardware:semiconductors",
    "aliases": [
      "op amp"
    ],
    "attributes": {
      "kind": "analog_ic"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E110",
    "char": "",
    "ligature": ":op_amp:",
    "shortcode": ":op_amp:",
    "glyph_name": "hardware_op_amp",
    "glyph_base": "op_amp",
    "svg": "glyphs/mono/op_amp.svg",
    "color_svg": "glyphs/color/op_amp.svg",
    "iso_svg": "glyphs/iso/op_amp.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Operational amplifier"
  },
  {
    "id": "hardware:oscillator",
    "label": "Oscillator",
    "category": "semiconductor",
    "system": "timing",
    "parent": "hardware:semiconductors",
    "aliases": [
      "clock oscillator"
    ],
    "attributes": {
      "kind": "timing"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E111",
    "char": "",
    "ligature": ":oscillator:",
    "shortcode": ":oscillator:",
    "glyph_name": "hardware_oscillator",
    "glyph_base": "oscillator",
    "svg": "glyphs/mono/oscillator.svg",
    "color_svg": "glyphs/color/oscillator.svg",
    "iso_svg": "glyphs/iso/oscillator.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Oscillator"
  },
  {
    "id": "hardware:crystal",
    "label": "Crystal resonator",
    "category": "passive_component",
    "system": "timing",
    "parent": "hardware:passive_components",
    "aliases": [
      "quartz crystal"
    ],
    "attributes": {
      "kind": "timing"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E112",
    "char": "",
    "ligature": ":crystal:",
    "shortcode": ":crystal:",
    "glyph_name": "hardware_crystal",
    "glyph_base": "crystal",
    "svg": "glyphs/mono/crystal.svg",
    "color_svg": "glyphs/color/crystal.svg",
    "iso_svg": "glyphs/iso/crystal.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Crystal resonator"
  },
  {
    "id": "hardware:logic_ic",
    "label": "Logic IC",
    "category": "semiconductor",
    "system": "digital",
    "parent": "hardware:semiconductors",
    "aliases": [
      "logic chip"
    ],
    "attributes": {
      "kind": "digital_ic"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E113",
    "char": "",
    "ligature": ":logic_ic:",
    "shortcode": ":logic_ic:",
    "glyph_name": "hardware_logic_ic",
    "glyph_base": "logic_ic",
    "svg": "glyphs/mono/logic_ic.svg",
    "color_svg": "glyphs/color/logic_ic.svg",
    "iso_svg": "glyphs/iso/logic_ic.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Logic IC"
  },
  {
    "id": "hardware:microcontroller",
    "label": "Microcontroller",
    "category": "semiconductor",
    "system": "digital",
    "parent": "hardware:semiconductors",
    "aliases": [
      "MCU"
    ],
    "attributes": {
      "kind": "processor"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E114",
    "char": "",
    "ligature": ":microcontroller:",
    "shortcode": ":microcontroller:",
    "glyph_name": "hardware_microcontroller",
    "glyph_base": "microcontroller",
    "svg": "glyphs/mono/microcontroller.svg",
    "color_svg": "glyphs/color/microcontroller.svg",
    "iso_svg": "glyphs/iso/microcontroller.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Microcontroller"
  },
  {
    "id": "hardware:microprocessor",
    "label": "Microprocessor",
    "category": "semiconductor",
    "system": "digital",
    "parent": "hardware:semiconductors",
    "aliases": [
      "CPU"
    ],
    "attributes": {
      "kind": "processor"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E115",
    "char": "",
    "ligature": ":microprocessor:",
    "shortcode": ":microprocessor:",
    "glyph_name": "hardware_microprocessor",
    "glyph_base": "microprocessor",
    "svg": "glyphs/mono/microprocessor.svg",
    "color_svg": "glyphs/color/microprocessor.svg",
    "iso_svg": "glyphs/iso/microprocessor.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Microprocessor"
  },
  {
    "id": "hardware:fpga",
    "label": "FPGA",
    "category": "semiconductor",
    "system": "digital",
    "parent": "hardware:semiconductors",
    "aliases": [
      "field-programmable gate array"
    ],
    "attributes": {
      "kind": "programmable_logic"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E116",
    "char": "",
    "ligature": ":fpga:",
    "shortcode": ":fpga:",
    "glyph_name": "hardware_fpga",
    "glyph_base": "fpga",
    "svg": "glyphs/mono/fpga.svg",
    "color_svg": "glyphs/color/fpga.svg",
    "iso_svg": "glyphs/iso/fpga.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "FPGA"
  },
  {
    "id": "hardware:dip",
    "label": "Dual in-line package",
    "category": "package",
    "system": "mechanical",
    "parent": "hardware:ic_packages",
    "aliases": [
      "DIP"
    ],
    "attributes": {
      "pins": "dual_row"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E117",
    "char": "",
    "ligature": ":dip:",
    "shortcode": ":dip:",
    "glyph_name": "hardware_dip",
    "glyph_base": "dip",
    "svg": "glyphs/mono/dip.svg",
    "color_svg": "glyphs/color/dip.svg",
    "iso_svg": "glyphs/iso/dip.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Dual in-line package"
  },
  {
    "id": "hardware:soic",
    "label": "Small-outline integrated circuit package",
    "category": "package",
    "system": "mechanical",
    "parent": "hardware:ic_packages",
    "aliases": [
      "SOIC"
    ],
    "attributes": {
      "pins": "dual_row"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E118",
    "char": "",
    "ligature": ":soic:",
    "shortcode": ":soic:",
    "glyph_name": "hardware_soic",
    "glyph_base": "soic",
    "svg": "glyphs/mono/soic.svg",
    "color_svg": "glyphs/color/soic.svg",
    "iso_svg": "glyphs/iso/soic.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Small-outline integrated circuit package"
  },
  {
    "id": "hardware:qfp",
    "label": "Quad flat package",
    "category": "package",
    "system": "mechanical",
    "parent": "hardware:ic_packages",
    "aliases": [
      "QFP"
    ],
    "attributes": {
      "pins": "four_sided"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E119",
    "char": "",
    "ligature": ":qfp:",
    "shortcode": ":qfp:",
    "glyph_name": "hardware_qfp",
    "glyph_base": "qfp",
    "svg": "glyphs/mono/qfp.svg",
    "color_svg": "glyphs/color/qfp.svg",
    "iso_svg": "glyphs/iso/qfp.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Quad flat package"
  },
  {
    "id": "hardware:qfn",
    "label": "Quad flat no-lead package",
    "category": "package",
    "system": "mechanical",
    "parent": "hardware:ic_packages",
    "aliases": [
      "QFN"
    ],
    "attributes": {
      "pins": "four_sided",
      "exposed_pad": true
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E11A",
    "char": "",
    "ligature": ":qfn:",
    "shortcode": ":qfn:",
    "glyph_name": "hardware_qfn",
    "glyph_base": "qfn",
    "svg": "glyphs/mono/qfn.svg",
    "color_svg": "glyphs/color/qfn.svg",
    "iso_svg": "glyphs/iso/qfn.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Quad flat no-lead package"
  },
  {
    "id": "hardware:bga",
    "label": "Ball grid array package",
    "category": "package",
    "system": "mechanical",
    "parent": "hardware:ic_packages",
    "aliases": [
      "BGA"
    ],
    "attributes": {
      "pins": "underside_grid"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E11B",
    "char": "",
    "ligature": ":bga:",
    "shortcode": ":bga:",
    "glyph_name": "hardware_bga",
    "glyph_base": "bga",
    "svg": "glyphs/mono/bga.svg",
    "color_svg": "glyphs/color/bga.svg",
    "iso_svg": "glyphs/iso/bga.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Ball grid array package"
  },
  {
    "id": "hardware:lga",
    "label": "Land grid array package",
    "category": "package",
    "system": "mechanical",
    "parent": "hardware:ic_packages",
    "aliases": [
      "LGA"
    ],
    "attributes": {
      "pins": "underside_land_grid"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E11C",
    "char": "",
    "ligature": ":lga:",
    "shortcode": ":lga:",
    "glyph_name": "hardware_lga",
    "glyph_base": "lga",
    "svg": "glyphs/mono/lga.svg",
    "color_svg": "glyphs/color/lga.svg",
    "iso_svg": "glyphs/iso/lga.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Land grid array package"
  },
  {
    "id": "hardware:to220",
    "label": "TO-220 package",
    "category": "package",
    "system": "mechanical",
    "parent": "hardware:ic_packages",
    "aliases": [
      "TO220"
    ],
    "attributes": {
      "pins": "through_hole"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E11D",
    "char": "",
    "ligature": ":to220:",
    "shortcode": ":to220:",
    "glyph_name": "hardware_to220",
    "glyph_base": "to220",
    "svg": "glyphs/mono/to220.svg",
    "color_svg": "glyphs/color/to220.svg",
    "iso_svg": "glyphs/iso/to220.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "TO-220 package"
  },
  {
    "id": "hardware:pcb",
    "label": "Printed circuit board",
    "category": "board",
    "system": "pcb",
    "parent": "hardware:pcb_features",
    "aliases": [
      "PCB",
      "circuit board"
    ],
    "attributes": {
      "layers": "variable"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E11E",
    "char": "",
    "ligature": ":pcb:",
    "shortcode": ":pcb:",
    "glyph_name": "hardware_pcb",
    "glyph_base": "pcb",
    "svg": "glyphs/mono/pcb.svg",
    "color_svg": "glyphs/color/pcb.svg",
    "iso_svg": "glyphs/iso/pcb.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference",
      "open_hardware"
    ],
    "accessible_label": "Printed circuit board"
  },
  {
    "id": "hardware:substrate",
    "label": "PCB substrate",
    "category": "pcb_feature",
    "system": "pcb",
    "parent": "hardware:pcb_features",
    "aliases": [
      "board substrate"
    ],
    "attributes": {
      "material": "laminate"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E11F",
    "char": "",
    "ligature": ":substrate:",
    "shortcode": ":substrate:",
    "glyph_name": "hardware_substrate",
    "glyph_base": "substrate",
    "svg": "glyphs/mono/substrate.svg",
    "color_svg": "glyphs/color/substrate.svg",
    "iso_svg": "glyphs/iso/substrate.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "PCB substrate"
  },
  {
    "id": "hardware:copper_layer",
    "label": "Copper layer",
    "category": "pcb_feature",
    "system": "pcb",
    "parent": "hardware:pcb_features",
    "aliases": [
      "copper pour"
    ],
    "attributes": {
      "material": "copper"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E120",
    "char": "",
    "ligature": ":copper_layer:",
    "shortcode": ":copper_layer:",
    "glyph_name": "hardware_copper_layer",
    "glyph_base": "copper_layer",
    "svg": "glyphs/mono/copper_layer.svg",
    "color_svg": "glyphs/color/copper_layer.svg",
    "iso_svg": "glyphs/iso/copper_layer.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Copper layer"
  },
  {
    "id": "hardware:solder_mask",
    "label": "Solder mask",
    "category": "pcb_feature",
    "system": "pcb",
    "parent": "hardware:pcb_features",
    "aliases": [
      "mask"
    ],
    "attributes": {
      "material": "polymer"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E121",
    "char": "",
    "ligature": ":solder_mask:",
    "shortcode": ":solder_mask:",
    "glyph_name": "hardware_solder_mask",
    "glyph_base": "solder_mask",
    "svg": "glyphs/mono/solder_mask.svg",
    "color_svg": "glyphs/color/solder_mask.svg",
    "iso_svg": "glyphs/iso/solder_mask.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Solder mask"
  },
  {
    "id": "hardware:silkscreen",
    "label": "Silkscreen",
    "category": "pcb_feature",
    "system": "pcb",
    "parent": "hardware:pcb_features",
    "aliases": [
      "legend"
    ],
    "attributes": {
      "material": "ink"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E122",
    "char": "",
    "ligature": ":silkscreen:",
    "shortcode": ":silkscreen:",
    "glyph_name": "hardware_silkscreen",
    "glyph_base": "silkscreen",
    "svg": "glyphs/mono/silkscreen.svg",
    "color_svg": "glyphs/color/silkscreen.svg",
    "iso_svg": "glyphs/iso/silkscreen.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Silkscreen"
  },
  {
    "id": "hardware:trace",
    "label": "Copper trace",
    "category": "pcb_feature",
    "system": "pcb",
    "parent": "hardware:pcb_features",
    "aliases": [
      "track"
    ],
    "attributes": {
      "kind": "conductor"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E123",
    "char": "",
    "ligature": ":trace:",
    "shortcode": ":trace:",
    "glyph_name": "hardware_trace",
    "glyph_base": "trace",
    "svg": "glyphs/mono/trace.svg",
    "color_svg": "glyphs/color/trace.svg",
    "iso_svg": "glyphs/iso/trace.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Copper trace"
  },
  {
    "id": "hardware:differential_pair",
    "label": "Differential pair",
    "category": "pcb_feature",
    "system": "signal",
    "parent": "hardware:pcb_features",
    "aliases": [
      "matched pair"
    ],
    "attributes": {
      "kind": "signal_route"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E124",
    "char": "",
    "ligature": ":differential_pair:",
    "shortcode": ":differential_pair:",
    "glyph_name": "hardware_differential_pair",
    "glyph_base": "differential_pair",
    "svg": "glyphs/mono/differential_pair.svg",
    "color_svg": "glyphs/color/differential_pair.svg",
    "iso_svg": "glyphs/iso/differential_pair.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Differential pair"
  },
  {
    "id": "hardware:ground_plane",
    "label": "Ground plane",
    "category": "pcb_feature",
    "system": "power",
    "parent": "hardware:pcb_features",
    "aliases": [
      "ground pour"
    ],
    "attributes": {
      "kind": "plane"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E125",
    "char": "",
    "ligature": ":ground_plane:",
    "shortcode": ":ground_plane:",
    "glyph_name": "hardware_ground_plane",
    "glyph_base": "ground_plane",
    "svg": "glyphs/mono/ground_plane.svg",
    "color_svg": "glyphs/color/ground_plane.svg",
    "iso_svg": "glyphs/iso/ground_plane.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Ground plane"
  },
  {
    "id": "hardware:via",
    "label": "Via",
    "category": "pcb_feature",
    "system": "pcb",
    "parent": "hardware:pcb_features",
    "aliases": [
      "plated via"
    ],
    "attributes": {
      "kind": "interconnect"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E126",
    "char": "",
    "ligature": ":via:",
    "shortcode": ":via:",
    "glyph_name": "hardware_via",
    "glyph_base": "via",
    "svg": "glyphs/mono/via.svg",
    "color_svg": "glyphs/color/via.svg",
    "iso_svg": "glyphs/iso/via.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Via"
  },
  {
    "id": "hardware:plated_through_hole",
    "label": "Plated through-hole",
    "category": "pcb_feature",
    "system": "pcb",
    "parent": "hardware:pcb_features",
    "aliases": [
      "PTH"
    ],
    "attributes": {
      "kind": "mounting_interconnect"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E127",
    "char": "",
    "ligature": ":plated_through_hole:",
    "shortcode": ":plated_through_hole:",
    "glyph_name": "hardware_plated_through_hole",
    "glyph_base": "plated_through_hole",
    "svg": "glyphs/mono/plated_through_hole.svg",
    "color_svg": "glyphs/color/plated_through_hole.svg",
    "iso_svg": "glyphs/iso/plated_through_hole.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Plated through-hole"
  },
  {
    "id": "hardware:pad",
    "label": "Solder pad",
    "category": "pcb_feature",
    "system": "pcb",
    "parent": "hardware:pcb_features",
    "aliases": [
      "land"
    ],
    "attributes": {
      "kind": "connection"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E128",
    "char": "",
    "ligature": ":pad:",
    "shortcode": ":pad:",
    "glyph_name": "hardware_pad",
    "glyph_base": "pad",
    "svg": "glyphs/mono/pad.svg",
    "color_svg": "glyphs/color/pad.svg",
    "iso_svg": "glyphs/iso/pad.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Solder pad"
  },
  {
    "id": "hardware:test_point",
    "label": "Test point",
    "category": "pcb_feature",
    "system": "test",
    "parent": "hardware:pcb_features",
    "aliases": [
      "probe point"
    ],
    "attributes": {
      "kind": "debug"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E129",
    "char": "",
    "ligature": ":test_point:",
    "shortcode": ":test_point:",
    "glyph_name": "hardware_test_point",
    "glyph_base": "test_point",
    "svg": "glyphs/mono/test_point.svg",
    "color_svg": "glyphs/color/test_point.svg",
    "iso_svg": "glyphs/iso/test_point.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Test point"
  },
  {
    "id": "hardware:jumper",
    "label": "Jumper",
    "category": "mechanical_component",
    "system": "configuration",
    "parent": "hardware:pcb_features",
    "aliases": [
      "header jumper"
    ],
    "attributes": {
      "kind": "configuration"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E12A",
    "char": "",
    "ligature": ":jumper:",
    "shortcode": ":jumper:",
    "glyph_name": "hardware_jumper",
    "glyph_base": "jumper",
    "svg": "glyphs/mono/jumper.svg",
    "color_svg": "glyphs/color/jumper.svg",
    "iso_svg": "glyphs/iso/jumper.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Jumper"
  },
  {
    "id": "hardware:mounting_hole",
    "label": "Mounting hole",
    "category": "mechanical_component",
    "system": "mechanical",
    "parent": "hardware:pcb_features",
    "aliases": [
      "fixing hole"
    ],
    "attributes": {
      "kind": "mounting"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E12B",
    "char": "",
    "ligature": ":mounting_hole:",
    "shortcode": ":mounting_hole:",
    "glyph_name": "hardware_mounting_hole",
    "glyph_base": "mounting_hole",
    "svg": "glyphs/mono/mounting_hole.svg",
    "color_svg": "glyphs/color/mounting_hole.svg",
    "iso_svg": "glyphs/iso/mounting_hole.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Mounting hole"
  },
  {
    "id": "hardware:fiducial",
    "label": "Fiducial marker",
    "category": "pcb_feature",
    "system": "assembly",
    "parent": "hardware:pcb_features",
    "aliases": [
      "fiducial"
    ],
    "attributes": {
      "kind": "optical_alignment"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E12C",
    "char": "",
    "ligature": ":fiducial:",
    "shortcode": ":fiducial:",
    "glyph_name": "hardware_fiducial",
    "glyph_base": "fiducial",
    "svg": "glyphs/mono/fiducial.svg",
    "color_svg": "glyphs/color/fiducial.svg",
    "iso_svg": "glyphs/iso/fiducial.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Fiducial marker"
  },
  {
    "id": "hardware:bga_footprint",
    "label": "BGA footprint",
    "category": "pcb_feature",
    "system": "assembly",
    "parent": "hardware:pcb_features",
    "aliases": [
      "BGA land pattern"
    ],
    "attributes": {
      "kind": "footprint"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E12D",
    "char": "",
    "ligature": ":bga_footprint:",
    "shortcode": ":bga_footprint:",
    "glyph_name": "hardware_bga_footprint",
    "glyph_base": "bga_footprint",
    "svg": "glyphs/mono/bga_footprint.svg",
    "color_svg": "glyphs/color/bga_footprint.svg",
    "iso_svg": "glyphs/iso/bga_footprint.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "BGA footprint"
  },
  {
    "id": "hardware:thermal_pad",
    "label": "Thermal pad",
    "category": "pcb_feature",
    "system": "thermal",
    "parent": "hardware:pcb_features",
    "aliases": [
      "exposed pad"
    ],
    "attributes": {
      "kind": "heat_transfer"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E12E",
    "char": "",
    "ligature": ":thermal_pad:",
    "shortcode": ":thermal_pad:",
    "glyph_name": "hardware_thermal_pad",
    "glyph_base": "thermal_pad",
    "svg": "glyphs/mono/thermal_pad.svg",
    "color_svg": "glyphs/color/thermal_pad.svg",
    "iso_svg": "glyphs/iso/thermal_pad.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Thermal pad"
  },
  {
    "id": "hardware:motherboard",
    "label": "Motherboard",
    "category": "board",
    "system": "computer",
    "parent": "hardware:computer_parts",
    "aliases": [
      "mainboard"
    ],
    "attributes": {
      "kind": "system_board"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E12F",
    "char": "",
    "ligature": ":motherboard:",
    "shortcode": ":motherboard:",
    "glyph_name": "hardware_motherboard",
    "glyph_base": "motherboard",
    "svg": "glyphs/mono/motherboard.svg",
    "color_svg": "glyphs/color/motherboard.svg",
    "iso_svg": "glyphs/iso/motherboard.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Motherboard"
  },
  {
    "id": "hardware:cpu",
    "label": "Central processing unit",
    "category": "semiconductor",
    "system": "computer",
    "parent": "hardware:computer_parts",
    "aliases": [
      "CPU",
      "processor"
    ],
    "attributes": {
      "kind": "processor"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E130",
    "char": "",
    "ligature": ":cpu:",
    "shortcode": ":cpu:",
    "glyph_name": "hardware_cpu",
    "glyph_base": "cpu",
    "svg": "glyphs/mono/cpu.svg",
    "color_svg": "glyphs/color/cpu.svg",
    "iso_svg": "glyphs/iso/cpu.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Central processing unit"
  },
  {
    "id": "hardware:gpu",
    "label": "Graphics processing unit",
    "category": "semiconductor",
    "system": "computer",
    "parent": "hardware:computer_parts",
    "aliases": [
      "GPU",
      "graphics card"
    ],
    "attributes": {
      "kind": "processor"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E131",
    "char": "",
    "ligature": ":gpu:",
    "shortcode": ":gpu:",
    "glyph_name": "hardware_gpu",
    "glyph_base": "gpu",
    "svg": "glyphs/mono/gpu.svg",
    "color_svg": "glyphs/color/gpu.svg",
    "iso_svg": "glyphs/iso/gpu.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Graphics processing unit"
  },
  {
    "id": "hardware:chipset",
    "label": "Chipset",
    "category": "semiconductor",
    "system": "computer",
    "parent": "hardware:computer_parts",
    "aliases": [
      "platform controller hub"
    ],
    "attributes": {
      "kind": "controller"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E132",
    "char": "",
    "ligature": ":chipset:",
    "shortcode": ":chipset:",
    "glyph_name": "hardware_chipset",
    "glyph_base": "chipset",
    "svg": "glyphs/mono/chipset.svg",
    "color_svg": "glyphs/color/chipset.svg",
    "iso_svg": "glyphs/iso/chipset.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Chipset"
  },
  {
    "id": "hardware:memory_module",
    "label": "Memory module",
    "category": "memory_module",
    "system": "memory",
    "parent": "hardware:memory",
    "aliases": [
      "RAM module"
    ],
    "attributes": {
      "kind": "module",
      "generation": "variable"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E164",
    "char": "",
    "ligature": ":memory_module:",
    "shortcode": ":memory_module:",
    "glyph_name": "hardware_memory_module",
    "glyph_base": "memory_module",
    "svg": "glyphs/mono/memory_module.svg",
    "color_svg": "glyphs/color/memory_module.svg",
    "iso_svg": "glyphs/iso/memory_module.svg",
    "external_ids": {},
    "sources": [
      "jedec"
    ],
    "accessible_label": "Memory module"
  },
  {
    "id": "hardware:ddr3_dimm",
    "label": "DDR3 DIMM",
    "category": "memory_module",
    "system": "memory",
    "parent": "hardware:memory",
    "aliases": [
      "DDR3 memory module"
    ],
    "attributes": {
      "memory_generation": "DDR3",
      "form_factor": "DIMM",
      "pin_count_common": 240
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E133",
    "char": "",
    "ligature": ":ddr3_dimm:",
    "shortcode": ":ddr3_dimm:",
    "glyph_name": "hardware_ddr3_dimm",
    "glyph_base": "ddr3_dimm",
    "svg": "glyphs/mono/ddr3_dimm.svg",
    "color_svg": "glyphs/color/ddr3_dimm.svg",
    "iso_svg": "glyphs/iso/ddr3_dimm.svg",
    "external_ids": {},
    "sources": [
      "jedec"
    ],
    "accessible_label": "DDR3 DIMM"
  },
  {
    "id": "hardware:ddr4_dimm",
    "label": "DDR4 DIMM",
    "category": "memory_module",
    "system": "memory",
    "parent": "hardware:memory",
    "aliases": [
      "DDR4 memory module"
    ],
    "attributes": {
      "memory_generation": "DDR4",
      "form_factor": "DIMM",
      "pin_count_common": 288
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E134",
    "char": "",
    "ligature": ":ddr4_dimm:",
    "shortcode": ":ddr4_dimm:",
    "glyph_name": "hardware_ddr4_dimm",
    "glyph_base": "ddr4_dimm",
    "svg": "glyphs/mono/ddr4_dimm.svg",
    "color_svg": "glyphs/color/ddr4_dimm.svg",
    "iso_svg": "glyphs/iso/ddr4_dimm.svg",
    "external_ids": {},
    "sources": [
      "jedec"
    ],
    "accessible_label": "DDR4 DIMM"
  },
  {
    "id": "hardware:ddr5_dimm",
    "label": "DDR5 DIMM",
    "category": "memory_module",
    "system": "memory",
    "parent": "hardware:memory",
    "aliases": [
      "DDR5 memory module"
    ],
    "attributes": {
      "memory_generation": "DDR5",
      "form_factor": "DIMM",
      "pin_count_common": 288
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E135",
    "char": "",
    "ligature": ":ddr5_dimm:",
    "shortcode": ":ddr5_dimm:",
    "glyph_name": "hardware_ddr5_dimm",
    "glyph_base": "ddr5_dimm",
    "svg": "glyphs/mono/ddr5_dimm.svg",
    "color_svg": "glyphs/color/ddr5_dimm.svg",
    "iso_svg": "glyphs/iso/ddr5_dimm.svg",
    "external_ids": {},
    "sources": [
      "jedec"
    ],
    "accessible_label": "DDR5 DIMM"
  },
  {
    "id": "hardware:ddr3_dimm_slot",
    "label": "DDR3 DIMM slot",
    "category": "slot",
    "system": "memory",
    "parent": "hardware:memory",
    "aliases": [
      "DDR3 socket"
    ],
    "attributes": {
      "memory_generation": "DDR3",
      "form_factor": "DIMM"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E136",
    "char": "",
    "ligature": ":ddr3_dimm_slot:",
    "shortcode": ":ddr3_dimm_slot:",
    "glyph_name": "hardware_ddr3_dimm_slot",
    "glyph_base": "ddr3_dimm_slot",
    "svg": "glyphs/mono/ddr3_dimm_slot.svg",
    "color_svg": "glyphs/color/ddr3_dimm_slot.svg",
    "iso_svg": "glyphs/iso/ddr3_dimm_slot.svg",
    "external_ids": {},
    "sources": [
      "jedec"
    ],
    "accessible_label": "DDR3 DIMM slot"
  },
  {
    "id": "hardware:ddr4_dimm_slot",
    "label": "DDR4 DIMM slot",
    "category": "slot",
    "system": "memory",
    "parent": "hardware:memory",
    "aliases": [
      "DDR4 socket"
    ],
    "attributes": {
      "memory_generation": "DDR4",
      "form_factor": "DIMM"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E137",
    "char": "",
    "ligature": ":ddr4_dimm_slot:",
    "shortcode": ":ddr4_dimm_slot:",
    "glyph_name": "hardware_ddr4_dimm_slot",
    "glyph_base": "ddr4_dimm_slot",
    "svg": "glyphs/mono/ddr4_dimm_slot.svg",
    "color_svg": "glyphs/color/ddr4_dimm_slot.svg",
    "iso_svg": "glyphs/iso/ddr4_dimm_slot.svg",
    "external_ids": {},
    "sources": [
      "jedec"
    ],
    "accessible_label": "DDR4 DIMM slot"
  },
  {
    "id": "hardware:ddr5_dimm_slot",
    "label": "DDR5 DIMM slot",
    "category": "slot",
    "system": "memory",
    "parent": "hardware:memory",
    "aliases": [
      "DDR5 socket"
    ],
    "attributes": {
      "memory_generation": "DDR5",
      "form_factor": "DIMM"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E138",
    "char": "",
    "ligature": ":ddr5_dimm_slot:",
    "shortcode": ":ddr5_dimm_slot:",
    "glyph_name": "hardware_ddr5_dimm_slot",
    "glyph_base": "ddr5_dimm_slot",
    "svg": "glyphs/mono/ddr5_dimm_slot.svg",
    "color_svg": "glyphs/color/ddr5_dimm_slot.svg",
    "iso_svg": "glyphs/iso/ddr5_dimm_slot.svg",
    "external_ids": {},
    "sources": [
      "jedec"
    ],
    "accessible_label": "DDR5 DIMM slot"
  },
  {
    "id": "hardware:pcie_x1_slot",
    "label": "PCI Express x1 slot",
    "category": "slot",
    "system": "expansion",
    "parent": "hardware:expansion",
    "aliases": [
      "PCIe x1"
    ],
    "attributes": {
      "bus": "PCIe",
      "physical_slot_width": "x1",
      "electrical_lane_count": "variable"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E139",
    "char": "",
    "ligature": ":pcie_x1_slot:",
    "shortcode": ":pcie_x1_slot:",
    "glyph_name": "hardware_pcie_x1_slot",
    "glyph_base": "pcie_x1_slot",
    "svg": "glyphs/mono/pcie_x1_slot.svg",
    "color_svg": "glyphs/color/pcie_x1_slot.svg",
    "iso_svg": "glyphs/iso/pcie_x1_slot.svg",
    "external_ids": {},
    "sources": [
      "pcie_sig"
    ],
    "accessible_label": "PCI Express x1 slot"
  },
  {
    "id": "hardware:pcie_x16_slot",
    "label": "PCI Express x16 slot",
    "category": "slot",
    "system": "expansion",
    "parent": "hardware:expansion",
    "aliases": [
      "PCIe x16"
    ],
    "attributes": {
      "bus": "PCIe",
      "physical_slot_width": "x16",
      "electrical_lane_count": "variable"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E13A",
    "char": "",
    "ligature": ":pcie_x16_slot:",
    "shortcode": ":pcie_x16_slot:",
    "glyph_name": "hardware_pcie_x16_slot",
    "glyph_base": "pcie_x16_slot",
    "svg": "glyphs/mono/pcie_x16_slot.svg",
    "color_svg": "glyphs/color/pcie_x16_slot.svg",
    "iso_svg": "glyphs/iso/pcie_x16_slot.svg",
    "external_ids": {},
    "sources": [
      "pcie_sig"
    ],
    "accessible_label": "PCI Express x16 slot"
  },
  {
    "id": "hardware:m2_socket",
    "label": "M.2 socket",
    "category": "socket",
    "system": "storage",
    "parent": "hardware:storage",
    "aliases": [
      "M2 slot"
    ],
    "attributes": {
      "form_factor": "M.2"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E13B",
    "char": "",
    "ligature": ":m2_socket:",
    "shortcode": ":m2_socket:",
    "glyph_name": "hardware_m2_socket",
    "glyph_base": "m2_socket",
    "svg": "glyphs/mono/m2_socket.svg",
    "color_svg": "glyphs/color/m2_socket.svg",
    "iso_svg": "glyphs/iso/m2_socket.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "M.2 socket"
  },
  {
    "id": "hardware:nvme_ssd",
    "label": "NVMe solid-state drive",
    "category": "storage_device",
    "system": "storage",
    "parent": "hardware:storage",
    "aliases": [
      "NVMe SSD"
    ],
    "attributes": {
      "protocol": "NVMe",
      "form_factor": "M.2"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E13C",
    "char": "",
    "ligature": ":nvme_ssd:",
    "shortcode": ":nvme_ssd:",
    "glyph_name": "hardware_nvme_ssd",
    "glyph_base": "nvme_ssd",
    "svg": "glyphs/mono/nvme_ssd.svg",
    "color_svg": "glyphs/color/nvme_ssd.svg",
    "iso_svg": "glyphs/iso/nvme_ssd.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "NVMe solid-state drive"
  },
  {
    "id": "hardware:sata_connector",
    "label": "SATA connector",
    "category": "connector",
    "system": "storage",
    "parent": "hardware:storage",
    "aliases": [
      "SATA data connector"
    ],
    "attributes": {
      "connector": "SATA"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E13D",
    "char": "",
    "ligature": ":sata_connector:",
    "shortcode": ":sata_connector:",
    "glyph_name": "hardware_sata_connector",
    "glyph_base": "sata_connector",
    "svg": "glyphs/mono/sata_connector.svg",
    "color_svg": "glyphs/color/sata_connector.svg",
    "iso_svg": "glyphs/iso/sata_connector.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "SATA connector"
  },
  {
    "id": "hardware:sata_ssd",
    "label": "SATA solid-state drive",
    "category": "storage_device",
    "system": "storage",
    "parent": "hardware:storage",
    "aliases": [
      "SATA SSD"
    ],
    "attributes": {
      "protocol": "SATA",
      "form_factor": "2_5_inch"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E13E",
    "char": "",
    "ligature": ":sata_ssd:",
    "shortcode": ":sata_ssd:",
    "glyph_name": "hardware_sata_ssd",
    "glyph_base": "sata_ssd",
    "svg": "glyphs/mono/sata_ssd.svg",
    "color_svg": "glyphs/color/sata_ssd.svg",
    "iso_svg": "glyphs/iso/sata_ssd.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "SATA solid-state drive"
  },
  {
    "id": "hardware:hdd",
    "label": "Hard disk drive",
    "category": "storage_device",
    "system": "storage",
    "parent": "hardware:storage",
    "aliases": [
      "HDD"
    ],
    "attributes": {
      "media": "magnetic"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E13F",
    "char": "",
    "ligature": ":hdd:",
    "shortcode": ":hdd:",
    "glyph_name": "hardware_hdd",
    "glyph_base": "hdd",
    "svg": "glyphs/mono/hdd.svg",
    "color_svg": "glyphs/color/hdd.svg",
    "iso_svg": "glyphs/iso/hdd.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Hard disk drive"
  },
  {
    "id": "hardware:usb_a",
    "label": "USB Type-A connector",
    "category": "connector",
    "system": "external_io",
    "parent": "hardware:ports",
    "aliases": [
      "USB-A"
    ],
    "attributes": {
      "connector": "USB_A"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E140",
    "char": "",
    "ligature": ":usb_a:",
    "shortcode": ":usb_a:",
    "glyph_name": "hardware_usb_a",
    "glyph_base": "usb_a",
    "svg": "glyphs/mono/usb_a.svg",
    "color_svg": "glyphs/color/usb_a.svg",
    "iso_svg": "glyphs/iso/usb_a.svg",
    "external_ids": {},
    "sources": [
      "usb_if"
    ],
    "accessible_label": "USB Type-A connector"
  },
  {
    "id": "hardware:usb_c",
    "label": "USB Type-C connector",
    "category": "connector",
    "system": "external_io",
    "parent": "hardware:ports",
    "aliases": [
      "USB-C"
    ],
    "attributes": {
      "connector": "USB_C"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E141",
    "char": "",
    "ligature": ":usb_c:",
    "shortcode": ":usb_c:",
    "glyph_name": "hardware_usb_c",
    "glyph_base": "usb_c",
    "svg": "glyphs/mono/usb_c.svg",
    "color_svg": "glyphs/color/usb_c.svg",
    "iso_svg": "glyphs/iso/usb_c.svg",
    "external_ids": {},
    "sources": [
      "usb_if"
    ],
    "accessible_label": "USB Type-C connector"
  },
  {
    "id": "hardware:hdmi",
    "label": "HDMI connector",
    "category": "connector",
    "system": "display",
    "parent": "hardware:ports",
    "aliases": [
      "HDMI port"
    ],
    "attributes": {
      "connector": "HDMI"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E142",
    "char": "",
    "ligature": ":hdmi:",
    "shortcode": ":hdmi:",
    "glyph_name": "hardware_hdmi",
    "glyph_base": "hdmi",
    "svg": "glyphs/mono/hdmi.svg",
    "color_svg": "glyphs/color/hdmi.svg",
    "iso_svg": "glyphs/iso/hdmi.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "HDMI connector"
  },
  {
    "id": "hardware:displayport",
    "label": "DisplayPort connector",
    "category": "connector",
    "system": "display",
    "parent": "hardware:ports",
    "aliases": [
      "DP"
    ],
    "attributes": {
      "connector": "DisplayPort"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E143",
    "char": "",
    "ligature": ":displayport:",
    "shortcode": ":displayport:",
    "glyph_name": "hardware_displayport",
    "glyph_base": "displayport",
    "svg": "glyphs/mono/displayport.svg",
    "color_svg": "glyphs/color/displayport.svg",
    "iso_svg": "glyphs/iso/displayport.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "DisplayPort connector"
  },
  {
    "id": "hardware:rj45",
    "label": "RJ45 / 8P8C connector",
    "category": "connector",
    "system": "networking",
    "parent": "hardware:ports",
    "aliases": [
      "Ethernet port",
      "8P8C"
    ],
    "attributes": {
      "connector": "8P8C"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E144",
    "char": "",
    "ligature": ":rj45:",
    "shortcode": ":rj45:",
    "glyph_name": "hardware_rj45",
    "glyph_base": "rj45",
    "svg": "glyphs/mono/rj45.svg",
    "color_svg": "glyphs/color/rj45.svg",
    "iso_svg": "glyphs/iso/rj45.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "RJ45 / 8P8C connector"
  },
  {
    "id": "hardware:audio_jack_35mm",
    "label": "3.5 mm audio jack",
    "category": "connector",
    "system": "audio",
    "parent": "hardware:ports",
    "aliases": [
      "headphone jack"
    ],
    "attributes": {
      "connector": "TRS_TRRS"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E145",
    "char": "",
    "ligature": ":audio_jack_35mm:",
    "shortcode": ":audio_jack_35mm:",
    "glyph_name": "hardware_audio_jack_35mm",
    "glyph_base": "audio_jack_35mm",
    "svg": "glyphs/mono/audio_jack_35mm.svg",
    "color_svg": "glyphs/color/audio_jack_35mm.svg",
    "iso_svg": "glyphs/iso/audio_jack_35mm.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "3.5 mm audio jack"
  },
  {
    "id": "hardware:atx_24pin",
    "label": "ATX 24-pin power connector",
    "category": "connector",
    "system": "power",
    "parent": "hardware:power",
    "aliases": [
      "mainboard power"
    ],
    "attributes": {
      "pin_count": 24
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E146",
    "char": "",
    "ligature": ":atx_24pin:",
    "shortcode": ":atx_24pin:",
    "glyph_name": "hardware_atx_24pin",
    "glyph_base": "atx_24pin",
    "svg": "glyphs/mono/atx_24pin.svg",
    "color_svg": "glyphs/color/atx_24pin.svg",
    "iso_svg": "glyphs/iso/atx_24pin.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "ATX 24-pin power connector"
  },
  {
    "id": "hardware:cpu_power_8pin",
    "label": "CPU 8-pin power connector",
    "category": "connector",
    "system": "power",
    "parent": "hardware:power",
    "aliases": [
      "EPS12V"
    ],
    "attributes": {
      "pin_count": 8
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E147",
    "char": "",
    "ligature": ":cpu_power_8pin:",
    "shortcode": ":cpu_power_8pin:",
    "glyph_name": "hardware_cpu_power_8pin",
    "glyph_base": "cpu_power_8pin",
    "svg": "glyphs/mono/cpu_power_8pin.svg",
    "color_svg": "glyphs/color/cpu_power_8pin.svg",
    "iso_svg": "glyphs/iso/cpu_power_8pin.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "CPU 8-pin power connector"
  },
  {
    "id": "hardware:pcie_power_8pin",
    "label": "PCIe 8-pin power connector",
    "category": "connector",
    "system": "power",
    "parent": "hardware:power",
    "aliases": [
      "GPU power connector"
    ],
    "attributes": {
      "pin_count": 8
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E148",
    "char": "",
    "ligature": ":pcie_power_8pin:",
    "shortcode": ":pcie_power_8pin:",
    "glyph_name": "hardware_pcie_power_8pin",
    "glyph_base": "pcie_power_8pin",
    "svg": "glyphs/mono/pcie_power_8pin.svg",
    "color_svg": "glyphs/color/pcie_power_8pin.svg",
    "iso_svg": "glyphs/iso/pcie_power_8pin.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "PCIe 8-pin power connector"
  },
  {
    "id": "hardware:fan",
    "label": "Cooling fan",
    "category": "cooling_component",
    "system": "thermal",
    "parent": "hardware:cooling",
    "aliases": [
      "case fan"
    ],
    "attributes": {
      "kind": "active_cooling"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E149",
    "char": "",
    "ligature": ":fan:",
    "shortcode": ":fan:",
    "glyph_name": "hardware_fan",
    "glyph_base": "fan",
    "svg": "glyphs/mono/fan.svg",
    "color_svg": "glyphs/color/fan.svg",
    "iso_svg": "glyphs/iso/fan.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Cooling fan"
  },
  {
    "id": "hardware:heatsink",
    "label": "Heatsink",
    "category": "cooling_component",
    "system": "thermal",
    "parent": "hardware:cooling",
    "aliases": [
      "heat sink"
    ],
    "attributes": {
      "kind": "passive_cooling"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E14A",
    "char": "",
    "ligature": ":heatsink:",
    "shortcode": ":heatsink:",
    "glyph_name": "hardware_heatsink",
    "glyph_base": "heatsink",
    "svg": "glyphs/mono/heatsink.svg",
    "color_svg": "glyphs/color/heatsink.svg",
    "iso_svg": "glyphs/iso/heatsink.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Heatsink"
  },
  {
    "id": "hardware:wifi_nic",
    "label": "Wi-Fi network interface card",
    "category": "expansion_card",
    "system": "networking",
    "parent": "hardware:networking",
    "aliases": [
      "wireless NIC"
    ],
    "attributes": {
      "kind": "network_adapter"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E14B",
    "char": "",
    "ligature": ":wifi_nic:",
    "shortcode": ":wifi_nic:",
    "glyph_name": "hardware_wifi_nic",
    "glyph_base": "wifi_nic",
    "svg": "glyphs/mono/wifi_nic.svg",
    "color_svg": "glyphs/color/wifi_nic.svg",
    "iso_svg": "glyphs/iso/wifi_nic.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Wi-Fi network interface card"
  },
  {
    "id": "hardware:ethernet_nic",
    "label": "Ethernet network interface card",
    "category": "expansion_card",
    "system": "networking",
    "parent": "hardware:networking",
    "aliases": [
      "Ethernet NIC"
    ],
    "attributes": {
      "kind": "network_adapter"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E14C",
    "char": "",
    "ligature": ":ethernet_nic:",
    "shortcode": ":ethernet_nic:",
    "glyph_name": "hardware_ethernet_nic",
    "glyph_base": "ethernet_nic",
    "svg": "glyphs/mono/ethernet_nic.svg",
    "color_svg": "glyphs/color/ethernet_nic.svg",
    "iso_svg": "glyphs/iso/ethernet_nic.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Ethernet network interface card"
  },
  {
    "id": "hardware:router",
    "label": "Router",
    "category": "network_device",
    "system": "networking",
    "parent": "hardware:networking",
    "aliases": [
      "network router"
    ],
    "attributes": {
      "kind": "network_device"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E14D",
    "char": "",
    "ligature": ":router:",
    "shortcode": ":router:",
    "glyph_name": "hardware_router",
    "glyph_base": "router",
    "svg": "glyphs/mono/router.svg",
    "color_svg": "glyphs/color/router.svg",
    "iso_svg": "glyphs/iso/router.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Router"
  },
  {
    "id": "hardware:switch",
    "label": "Network switch",
    "category": "network_device",
    "system": "networking",
    "parent": "hardware:networking",
    "aliases": [
      "Ethernet switch"
    ],
    "attributes": {
      "kind": "network_device"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E14E",
    "char": "",
    "ligature": ":switch:",
    "shortcode": ":switch:",
    "glyph_name": "hardware_switch",
    "glyph_base": "switch",
    "svg": "glyphs/mono/switch.svg",
    "color_svg": "glyphs/color/switch.svg",
    "iso_svg": "glyphs/iso/switch.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Network switch"
  },
  {
    "id": "hardware:antenna",
    "label": "Antenna",
    "category": "networking",
    "system": "radio",
    "parent": "hardware:networking",
    "aliases": [
      "RF antenna"
    ],
    "attributes": {
      "kind": "transducer"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E14F",
    "char": "",
    "ligature": ":antenna:",
    "shortcode": ":antenna:",
    "glyph_name": "hardware_antenna",
    "glyph_base": "antenna",
    "svg": "glyphs/mono/antenna.svg",
    "color_svg": "glyphs/color/antenna.svg",
    "iso_svg": "glyphs/iso/antenna.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Antenna"
  },
  {
    "id": "hardware:atx_psu",
    "label": "ATX power supply",
    "category": "power_supply",
    "system": "power",
    "parent": "hardware:power",
    "aliases": [
      "PSU"
    ],
    "attributes": {
      "kind": "AC_DC_supply"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E150",
    "char": "",
    "ligature": ":atx_psu:",
    "shortcode": ":atx_psu:",
    "glyph_name": "hardware_atx_psu",
    "glyph_base": "atx_psu",
    "svg": "glyphs/mono/atx_psu.svg",
    "color_svg": "glyphs/color/atx_psu.svg",
    "iso_svg": "glyphs/iso/atx_psu.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "ATX power supply"
  },
  {
    "id": "hardware:coin_cell_battery",
    "label": "Coin-cell battery",
    "category": "power_source",
    "system": "power",
    "parent": "hardware:power",
    "aliases": [
      "CMOS battery",
      "CR2032"
    ],
    "attributes": {
      "kind": "battery"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E151",
    "char": "",
    "ligature": ":coin_cell_battery:",
    "shortcode": ":coin_cell_battery:",
    "glyph_name": "hardware_coin_cell_battery",
    "glyph_base": "coin_cell_battery",
    "svg": "glyphs/mono/coin_cell_battery.svg",
    "color_svg": "glyphs/color/coin_cell_battery.svg",
    "iso_svg": "glyphs/iso/coin_cell_battery.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Coin-cell battery"
  },
  {
    "id": "hardware:usb_protocol",
    "label": "USB protocol",
    "category": "protocol",
    "system": "external_io",
    "parent": "hardware:protocols",
    "aliases": [
      "Universal Serial Bus"
    ],
    "attributes": {
      "kind": "protocol"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E152",
    "char": "",
    "ligature": ":usb_protocol:",
    "shortcode": ":usb_protocol:",
    "glyph_name": "hardware_usb_protocol",
    "glyph_base": "usb_protocol",
    "svg": "glyphs/mono/usb_protocol.svg",
    "color_svg": "glyphs/color/usb_protocol.svg",
    "iso_svg": "glyphs/iso/usb_protocol.svg",
    "external_ids": {},
    "sources": [
      "usb_if"
    ],
    "accessible_label": "USB protocol"
  },
  {
    "id": "hardware:pcie_protocol",
    "label": "PCI Express protocol",
    "category": "protocol",
    "system": "expansion",
    "parent": "hardware:protocols",
    "aliases": [
      "PCIe"
    ],
    "attributes": {
      "kind": "protocol"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E153",
    "char": "",
    "ligature": ":pcie_protocol:",
    "shortcode": ":pcie_protocol:",
    "glyph_name": "hardware_pcie_protocol",
    "glyph_base": "pcie_protocol",
    "svg": "glyphs/mono/pcie_protocol.svg",
    "color_svg": "glyphs/color/pcie_protocol.svg",
    "iso_svg": "glyphs/iso/pcie_protocol.svg",
    "external_ids": {},
    "sources": [
      "pcie_sig"
    ],
    "accessible_label": "PCI Express protocol"
  },
  {
    "id": "hardware:nvme_protocol",
    "label": "NVMe protocol",
    "category": "protocol",
    "system": "storage",
    "parent": "hardware:protocols",
    "aliases": [
      "Non-Volatile Memory Express"
    ],
    "attributes": {
      "kind": "protocol"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E154",
    "char": "",
    "ligature": ":nvme_protocol:",
    "shortcode": ":nvme_protocol:",
    "glyph_name": "hardware_nvme_protocol",
    "glyph_base": "nvme_protocol",
    "svg": "glyphs/mono/nvme_protocol.svg",
    "color_svg": "glyphs/color/nvme_protocol.svg",
    "iso_svg": "glyphs/iso/nvme_protocol.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "NVMe protocol"
  },
  {
    "id": "hardware:sata_protocol",
    "label": "SATA protocol",
    "category": "protocol",
    "system": "storage",
    "parent": "hardware:protocols",
    "aliases": [
      "Serial ATA"
    ],
    "attributes": {
      "kind": "protocol"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E155",
    "char": "",
    "ligature": ":sata_protocol:",
    "shortcode": ":sata_protocol:",
    "glyph_name": "hardware_sata_protocol",
    "glyph_base": "sata_protocol",
    "svg": "glyphs/mono/sata_protocol.svg",
    "color_svg": "glyphs/color/sata_protocol.svg",
    "iso_svg": "glyphs/iso/sata_protocol.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "SATA protocol"
  },
  {
    "id": "hardware:x86_64",
    "label": "x86-64 architecture",
    "category": "architecture",
    "system": "processor",
    "parent": "hardware:architectures",
    "aliases": [
      "AMD64"
    ],
    "attributes": {
      "kind": "ISA"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E156",
    "char": "",
    "ligature": ":x86_64:",
    "shortcode": ":x86_64:",
    "glyph_name": "hardware_x86_64",
    "glyph_base": "x86_64",
    "svg": "glyphs/mono/x86_64.svg",
    "color_svg": "glyphs/color/x86_64.svg",
    "iso_svg": "glyphs/iso/x86_64.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "x86-64 architecture"
  },
  {
    "id": "hardware:arm64",
    "label": "ARM64 architecture",
    "category": "architecture",
    "system": "processor",
    "parent": "hardware:architectures",
    "aliases": [
      "AArch64"
    ],
    "attributes": {
      "kind": "ISA"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E157",
    "char": "",
    "ligature": ":arm64:",
    "shortcode": ":arm64:",
    "glyph_name": "hardware_arm64",
    "glyph_base": "arm64",
    "svg": "glyphs/mono/arm64.svg",
    "color_svg": "glyphs/color/arm64.svg",
    "iso_svg": "glyphs/iso/arm64.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "ARM64 architecture"
  },
  {
    "id": "hardware:riscv",
    "label": "RISC-V architecture",
    "category": "architecture",
    "system": "processor",
    "parent": "hardware:architectures",
    "aliases": [
      "RISC-V"
    ],
    "attributes": {
      "kind": "ISA"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E158",
    "char": "",
    "ligature": ":riscv:",
    "shortcode": ":riscv:",
    "glyph_name": "hardware_riscv",
    "glyph_base": "riscv",
    "svg": "glyphs/mono/riscv.svg",
    "color_svg": "glyphs/color/riscv.svg",
    "iso_svg": "glyphs/iso/riscv.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "RISC-V architecture"
  },
  {
    "id": "hardware:usb_c_cable",
    "label": "USB-C cable",
    "category": "cable",
    "system": "external_io",
    "parent": "hardware:cables",
    "aliases": [
      "USB Type-C cable"
    ],
    "attributes": {
      "endpoint_a": "USB_C",
      "endpoint_b": "USB_C"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E159",
    "char": "",
    "ligature": ":usb_c_cable:",
    "shortcode": ":usb_c_cable:",
    "glyph_name": "hardware_usb_c_cable",
    "glyph_base": "usb_c_cable",
    "svg": "glyphs/mono/usb_c_cable.svg",
    "color_svg": "glyphs/color/usb_c_cable.svg",
    "iso_svg": "glyphs/iso/usb_c_cable.svg",
    "external_ids": {},
    "sources": [
      "usb_if"
    ],
    "accessible_label": "USB-C cable"
  },
  {
    "id": "hardware:sata_cable",
    "label": "SATA data cable",
    "category": "cable",
    "system": "storage",
    "parent": "hardware:cables",
    "aliases": [
      "Serial ATA cable"
    ],
    "attributes": {
      "endpoint_a": "SATA",
      "endpoint_b": "SATA"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E15A",
    "char": "",
    "ligature": ":sata_cable:",
    "shortcode": ":sata_cable:",
    "glyph_name": "hardware_sata_cable",
    "glyph_base": "sata_cable",
    "svg": "glyphs/mono/sata_cable.svg",
    "color_svg": "glyphs/color/sata_cable.svg",
    "iso_svg": "glyphs/iso/sata_cable.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "SATA data cable"
  },
  {
    "id": "hardware:ethernet_cable",
    "label": "Ethernet cable",
    "category": "cable",
    "system": "networking",
    "parent": "hardware:cables",
    "aliases": [
      "network cable"
    ],
    "attributes": {
      "endpoint_a": "8P8C",
      "endpoint_b": "8P8C"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": false,
    "codepoint": "U+E15B",
    "char": "",
    "ligature": ":ethernet_cable:",
    "shortcode": ":ethernet_cable:",
    "glyph_name": "hardware_ethernet_cable",
    "glyph_base": "ethernet_cable",
    "svg": "glyphs/mono/ethernet_cable.svg",
    "color_svg": "glyphs/color/ethernet_cable.svg",
    "iso_svg": "glyphs/iso/ethernet_cable.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "Ethernet cable"
  },
  {
    "id": "hardware:isa_slot",
    "label": "ISA slot",
    "category": "slot",
    "system": "expansion",
    "parent": "hardware:historic",
    "aliases": [
      "Industry Standard Architecture"
    ],
    "attributes": {
      "bus": "ISA"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E15C",
    "char": "",
    "ligature": ":isa_slot:",
    "shortcode": ":isa_slot:",
    "glyph_name": "hardware_isa_slot",
    "glyph_base": "isa_slot",
    "svg": "glyphs/mono/isa_slot.svg",
    "color_svg": "glyphs/color/isa_slot.svg",
    "iso_svg": "glyphs/iso/isa_slot.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "ISA slot"
  },
  {
    "id": "hardware:pci_slot",
    "label": "PCI slot",
    "category": "slot",
    "system": "expansion",
    "parent": "hardware:historic",
    "aliases": [
      "Peripheral Component Interconnect"
    ],
    "attributes": {
      "bus": "PCI"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E15D",
    "char": "",
    "ligature": ":pci_slot:",
    "shortcode": ":pci_slot:",
    "glyph_name": "hardware_pci_slot",
    "glyph_base": "pci_slot",
    "svg": "glyphs/mono/pci_slot.svg",
    "color_svg": "glyphs/color/pci_slot.svg",
    "iso_svg": "glyphs/iso/pci_slot.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "PCI slot"
  },
  {
    "id": "hardware:agp_slot",
    "label": "AGP slot",
    "category": "slot",
    "system": "expansion",
    "parent": "hardware:historic",
    "aliases": [
      "Accelerated Graphics Port"
    ],
    "attributes": {
      "bus": "AGP"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E15E",
    "char": "",
    "ligature": ":agp_slot:",
    "shortcode": ":agp_slot:",
    "glyph_name": "hardware_agp_slot",
    "glyph_base": "agp_slot",
    "svg": "glyphs/mono/agp_slot.svg",
    "color_svg": "glyphs/color/agp_slot.svg",
    "iso_svg": "glyphs/iso/agp_slot.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "AGP slot"
  },
  {
    "id": "hardware:ide_connector",
    "label": "IDE / PATA connector",
    "category": "connector",
    "system": "storage",
    "parent": "hardware:historic",
    "aliases": [
      "PATA",
      "ATA ribbon connector"
    ],
    "attributes": {
      "interface": "PATA"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E15F",
    "char": "",
    "ligature": ":ide_connector:",
    "shortcode": ":ide_connector:",
    "glyph_name": "hardware_ide_connector",
    "glyph_base": "ide_connector",
    "svg": "glyphs/mono/ide_connector.svg",
    "color_svg": "glyphs/color/ide_connector.svg",
    "iso_svg": "glyphs/iso/ide_connector.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "IDE / PATA connector"
  },
  {
    "id": "hardware:scsi_connector",
    "label": "SCSI connector",
    "category": "connector",
    "system": "storage",
    "parent": "hardware:historic",
    "aliases": [
      "Small Computer System Interface"
    ],
    "attributes": {
      "interface": "SCSI"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E160",
    "char": "",
    "ligature": ":scsi_connector:",
    "shortcode": ":scsi_connector:",
    "glyph_name": "hardware_scsi_connector",
    "glyph_base": "scsi_connector",
    "svg": "glyphs/mono/scsi_connector.svg",
    "color_svg": "glyphs/color/scsi_connector.svg",
    "iso_svg": "glyphs/iso/scsi_connector.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "SCSI connector"
  },
  {
    "id": "hardware:vga",
    "label": "VGA connector",
    "category": "connector",
    "system": "display",
    "parent": "hardware:historic",
    "aliases": [
      "DE-15"
    ],
    "attributes": {
      "connector": "VGA"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E161",
    "char": "",
    "ligature": ":vga:",
    "shortcode": ":vga:",
    "glyph_name": "hardware_vga",
    "glyph_base": "vga",
    "svg": "glyphs/mono/vga.svg",
    "color_svg": "glyphs/color/vga.svg",
    "iso_svg": "glyphs/iso/vga.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "VGA connector"
  },
  {
    "id": "hardware:ps2",
    "label": "PS/2 connector",
    "category": "connector",
    "system": "input",
    "parent": "hardware:historic",
    "aliases": [
      "PS2"
    ],
    "attributes": {
      "connector": "mini_DIN_6"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E162",
    "char": "",
    "ligature": ":ps2:",
    "shortcode": ":ps2:",
    "glyph_name": "hardware_ps2",
    "glyph_base": "ps2",
    "svg": "glyphs/mono/ps2.svg",
    "color_svg": "glyphs/color/ps2.svg",
    "iso_svg": "glyphs/iso/ps2.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "PS/2 connector"
  },
  {
    "id": "hardware:sd_card",
    "label": "SD card",
    "category": "storage_medium",
    "system": "storage",
    "parent": "hardware:storage",
    "aliases": [
      "Secure Digital"
    ],
    "attributes": {
      "form_factor": "removable"
    },
    "interfaces": [],
    "compatible_with": [],
    "incompatible_with": [],
    "review_required": true,
    "codepoint": "U+E163",
    "char": "",
    "ligature": ":sd_card:",
    "shortcode": ":sd_card:",
    "glyph_name": "hardware_sd_card",
    "glyph_base": "sd_card",
    "svg": "glyphs/mono/sd_card.svg",
    "color_svg": "glyphs/color/sd_card.svg",
    "iso_svg": "glyphs/iso/sd_card.svg",
    "external_ids": {},
    "sources": [
      "hardware_reference"
    ],
    "accessible_label": "SD card"
  }
];
const groups = [
  {
    "id": "hardware:computer_hardware",
    "label": "Computer hardware",
    "parent": null
  },
  {
    "id": "hardware:passive_components",
    "label": "Passive components",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:semiconductors",
    "label": "Semiconductors",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:ic_packages",
    "label": "IC packages",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:pcb_features",
    "label": "PCB features",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:computer_parts",
    "label": "Computer parts",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:memory",
    "label": "Memory",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:expansion",
    "label": "Expansion slots and buses",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:storage",
    "label": "Storage",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:ports",
    "label": "External ports",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:power",
    "label": "Power",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:cooling",
    "label": "Cooling",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:networking",
    "label": "Networking",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:protocols",
    "label": "Interfaces and protocols",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:architectures",
    "label": "CPU architectures",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:cables",
    "label": "Cables",
    "parent": "hardware:computer_hardware"
  },
  {
    "id": "hardware:historic",
    "label": "Historic hardware",
    "parent": "hardware:computer_hardware"
  }
];
const relations = [
  {
    "from": "hardware:ddr3_dimm",
    "relation": "IS_A",
    "to": "hardware:memory_module"
  },
  {
    "from": "hardware:ddr4_dimm",
    "relation": "IS_A",
    "to": "hardware:memory_module"
  },
  {
    "from": "hardware:ddr5_dimm",
    "relation": "IS_A",
    "to": "hardware:memory_module"
  },
  {
    "from": "hardware:ddr3_dimm",
    "relation": "FITS_IN",
    "to": "hardware:ddr3_dimm_slot"
  },
  {
    "from": "hardware:ddr4_dimm",
    "relation": "FITS_IN",
    "to": "hardware:ddr4_dimm_slot"
  },
  {
    "from": "hardware:ddr5_dimm",
    "relation": "FITS_IN",
    "to": "hardware:ddr5_dimm_slot"
  },
  {
    "from": "hardware:ddr3_dimm",
    "relation": "INCOMPATIBLE_WITH",
    "to": "hardware:ddr4_dimm_slot"
  },
  {
    "from": "hardware:ddr3_dimm",
    "relation": "INCOMPATIBLE_WITH",
    "to": "hardware:ddr5_dimm_slot"
  },
  {
    "from": "hardware:ddr4_dimm",
    "relation": "INCOMPATIBLE_WITH",
    "to": "hardware:ddr3_dimm_slot"
  },
  {
    "from": "hardware:ddr4_dimm",
    "relation": "INCOMPATIBLE_WITH",
    "to": "hardware:ddr5_dimm_slot"
  },
  {
    "from": "hardware:ddr5_dimm",
    "relation": "INCOMPATIBLE_WITH",
    "to": "hardware:ddr3_dimm_slot"
  },
  {
    "from": "hardware:ddr5_dimm",
    "relation": "INCOMPATIBLE_WITH",
    "to": "hardware:ddr4_dimm_slot"
  },
  {
    "from": "hardware:cpu",
    "relation": "PACKAGED_AS",
    "to": "hardware:lga"
  },
  {
    "from": "hardware:motherboard",
    "relation": "CONTAINS",
    "to": "hardware:cpu"
  },
  {
    "from": "hardware:motherboard",
    "relation": "CONTAINS",
    "to": "hardware:pcie_x16_slot"
  },
  {
    "from": "hardware:motherboard",
    "relation": "CONTAINS",
    "to": "hardware:m2_socket"
  },
  {
    "from": "hardware:motherboard",
    "relation": "CONTAINS",
    "to": "hardware:sata_connector"
  },
  {
    "from": "hardware:motherboard",
    "relation": "CONTAINS",
    "to": "hardware:atx_24pin"
  },
  {
    "from": "hardware:motherboard",
    "relation": "CONTAINS",
    "to": "hardware:cpu_power_8pin"
  },
  {
    "from": "hardware:nvme_ssd",
    "relation": "USES_INTERFACE",
    "to": "hardware:m2_socket"
  },
  {
    "from": "hardware:nvme_ssd",
    "relation": "CARRIES_PROTOCOL",
    "to": "hardware:nvme_protocol"
  },
  {
    "from": "hardware:sata_ssd",
    "relation": "CONNECTS_TO",
    "to": "hardware:sata_connector"
  },
  {
    "from": "hardware:sata_ssd",
    "relation": "CARRIES_PROTOCOL",
    "to": "hardware:sata_protocol"
  },
  {
    "from": "hardware:usb_c",
    "relation": "CARRIES_PROTOCOL",
    "to": "hardware:usb_protocol"
  },
  {
    "from": "hardware:usb_a",
    "relation": "CARRIES_PROTOCOL",
    "to": "hardware:usb_protocol"
  },
  {
    "from": "hardware:pcie_x1_slot",
    "relation": "CARRIES_PROTOCOL",
    "to": "hardware:pcie_protocol"
  },
  {
    "from": "hardware:pcie_x16_slot",
    "relation": "CARRIES_PROTOCOL",
    "to": "hardware:pcie_protocol"
  },
  {
    "from": "hardware:fan",
    "relation": "POWERED_BY",
    "to": "hardware:atx_psu"
  },
  {
    "from": "hardware:heatsink",
    "relation": "COOLS",
    "to": "hardware:cpu"
  },
  {
    "from": "hardware:gpu",
    "relation": "PACKAGED_AS",
    "to": "hardware:bga"
  },
  {
    "from": "hardware:usb_c_cable",
    "relation": "CONNECTS_TO",
    "to": "hardware:usb_c"
  },
  {
    "from": "hardware:sata_cable",
    "relation": "CONNECTS_TO",
    "to": "hardware:sata_connector"
  },
  {
    "from": "hardware:ethernet_cable",
    "relation": "CONNECTS_TO",
    "to": "hardware:rj45"
  },
  {
    "from": "hardware:ddr4_dimm",
    "relation": "PREDECESSOR_OF",
    "to": "hardware:ddr5_dimm"
  }
];
const byId = new Map(registry.map((item) => [item.id, item]));
const byShortcode = new Map(registry.map((item) => [item.shortcode, item]));
function get(id) { return byId.get(id) || null; }
function resolveShortcode(shortcode) { return byShortcode.get(shortcode) || null; }
function unicodeFor(id) { const item = get(id); return item ? item.char : null; }
function search(query) { const needle = String(query || '').toLowerCase(); return registry.filter((item) => { const attributes = Object.entries(item.attributes || {}).flat(); const externalIds = Object.entries(item.external_ids || {}).flat(); return [item.id, item.label, item.shortcode, ...item.aliases, ...attributes, ...externalIds].some((value) => String(value).toLowerCase().includes(needle)); }); }
function parents(id) { const item = get(id); return item && item.parent ? [item.parent] : []; }
function children(id) { return registry.filter((item) => item.parent === id); }
function relationsFor(id) { return relations.filter((edge) => edge.from === id || edge.to === id); }
function compatibleWith(id) { return relations.filter((edge) => edge.from === id && ['COMPATIBLE_WITH', 'FITS_IN'].includes(edge.relation)).map((edge) => get(edge.to)).filter(Boolean); }
function connectionsFor(id) { return relationsFor(id).filter((edge) => ['CONNECTS_TO', 'CARRIES_PROTOCOL', 'USES_INTERFACE'].includes(edge.relation)); }
module.exports = { registry, groups, relations, get, resolveShortcode, unicodeFor, search, parents, children, relationsFor, compatibleWith, connectionsFor };
