#!/usr/bin/env python3
"""Generate CSV registries and JS/TypeScript views from the hardware ontology."""

from __future__ import annotations

import csv
import json
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]


def load() -> tuple[dict, dict]:
    return (
        yaml.safe_load((ROOT / "ontology/hardware.yaml").read_text()),
        yaml.safe_load((ROOT / "ontology/relations.yaml").read_text()),
    )


def assemblies() -> list[dict]:
    return [yaml.safe_load(path.read_text(encoding="utf-8")) for path in sorted((ROOT / "assemblies").glob("*.yaml"))]


def project_version() -> str:
    return str(yaml.safe_load((ROOT / "project.yaml").read_text())["version"])


def record(item: dict) -> dict:
    cp = str(item["unicode_pua"]).upper()
    return {
        "id": item["id"], "label": item["label"], "category": item["category"], "system": item["system"],
        "parent": item["parent"], "aliases": item["aliases"], "attributes": item["attributes"],
        "interfaces": item["interfaces"], "compatible_with": item["compatible_with"],
        "incompatible_with": item["incompatible_with"], "review_required": item["review_required"],
        "codepoint": f"U+{cp}", "char": chr(int(cp, 16)), "ligature": item["ligature"], "shortcode": item["shortcode"],
        "glyph_name": "hardware_" + item["id"].split(":", 1)[1], "glyph_base": item["glyph"]["base"],
        "svg": item["glyph"]["monochrome"], "color_svg": item["glyph"]["color"],
        "iso_svg": "glyphs/iso/" + item["id"].split(":", 1)[1] + ".svg",
        "technical_top_svg": "glyphs/technical/top/" + item["id"].split(":", 1)[1] + ".svg",
        "technical_front_svg": "glyphs/technical/front/" + item["id"].split(":", 1)[1] + ".svg",
        "technical_side_svg": "glyphs/technical/side/" + item["id"].split(":", 1)[1] + ".svg",
        "technical_iso_svg": "glyphs/technical/isometric/" + item["id"].split(":", 1)[1] + ".svg",
        "external_ids": item.get("external_ids", {}), "sources": item["provenance"],
        "accessible_label": item["label"],
    }


def write_csv(path: Path, rows: list[dict], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    source, relation_data = load()
    scene_data = assemblies()
    rows = [record(item) for item in source["objects"]]
    write_csv(ROOT / "registry/codepoints.csv", rows, ["id", "label", "category", "system", "codepoint", "char", "glyph_name", "svg", "color_svg", "iso_svg"])
    write_csv(ROOT / "registry/ligatures.csv", rows, ["id", "label", "ligature", "glyph_name", "codepoint"])
    aliases = []
    for row in rows:
        aliases.extend([{"id": row["id"], "alias": row["label"], "kind": "label"}, {"id": row["id"], "alias": row["shortcode"], "kind": "shortcode"}])
        aliases.extend({"id": row["id"], "alias": alias, "kind": "alias"} for alias in row["aliases"])
    write_csv(ROOT / "registry/aliases.csv", aliases, ["id", "alias", "kind"])
    write_csv(ROOT / "registry/compatibility.csv", relation_data.get("edges", []), ["from", "relation", "to"])
    write_csv(ROOT / "registry/groups.csv", source["groups"], ["id", "label", "parent"])

    groups = source["groups"]
    relations = relation_data.get("edges", [])
    package = """/** Generated by scripts/generate_registry.py. */
const registry = %s;
const groups = %s;
const relations = %s;
const assemblies = %s;
const byId = new Map(registry.map((item) => [item.id, item]));
const byShortcode = new Map(registry.map((item) => [item.shortcode, item]));
function get(id) { return byId.get(id) || null; }
function resolveShortcode(shortcode) { return byShortcode.get(shortcode) || null; }
function unicodeFor(id) { const item = get(id); return item ? item.char : null; }
function search(query) { const needle = String(query || '').toLowerCase(); return registry.filter((item) => { const attributes = Object.entries(item.attributes || {}).flat(); const externalIds = Object.entries(item.external_ids || {}).flat(); return [item.id, item.label, item.shortcode, ...item.aliases, ...attributes, ...externalIds].some((value) => String(value).toLowerCase().includes(needle)); }); }
function parents(id) { const item = get(id); return item && item.parent ? [item.parent] : []; }
function children(id) { return registry.filter((item) => item.parent === id); }
function relationsFor(id) { return relations.filter((edge) => edge.from === id || edge.to === id); }
function compatibleWith(id) { return relations.filter((edge) => edge.from === id && ['COMPATIBLE_WITH', 'FITS_IN'].includes(edge.relation)).map((edge) => get(edge.to)).filter(Boolean); }
function connectionsFor(id) { return relationsFor(id).filter((edge) => ['CONNECTS_TO', 'CARRIES_PROTOCOL', 'USES_INTERFACE'].includes(edge.relation)); }
function assembly(id) { return assemblies.find((scene) => scene.id === id) || null; }
function instances(id) { const scene = assembly(id); return scene ? scene.layers.map((layer) => ({...layer, object_record: get(layer.object)})) : []; }
function objectForInstance(sceneId, instanceId) { return instances(sceneId).find((layer) => layer.instance === instanceId)?.object_record || null; }
module.exports = { registry, groups, relations, assemblies, get, resolveShortcode, unicodeFor, search, parents, children, relationsFor, compatibleWith, connectionsFor, assembly, instances, objectForInstance };
""" % (json.dumps(rows, ensure_ascii=False, indent=2), json.dumps(groups, ensure_ascii=False, indent=2), json.dumps(relations, ensure_ascii=False, indent=2), json.dumps(scene_data, ensure_ascii=False, indent=2))
    (ROOT / "packages/js/index.js").write_text(package, encoding="utf-8")
    (ROOT / "packages/js/index.d.ts").write_text("""export interface HardwareGroup { id: string; label: string; parent: string | null; }
export interface HardwareRecord { id: string; label: string; category: string; system: string; parent: string; aliases: string[]; attributes: Record<string, unknown>; interfaces: string[]; compatible_with: string[]; incompatible_with: string[]; review_required: boolean; codepoint: string; char: string; ligature: string; shortcode: string; glyph_name: string; glyph_base: string; svg: string; color_svg: string; iso_svg: string; external_ids: Record<string, string>; sources: string[]; accessible_label: string; }
export interface HardwareRelation { from: string; relation: string; to: string; }
export const registry: HardwareRecord[];
export const groups: HardwareGroup[];
export const relations: HardwareRelation[];
export function get(id: string): HardwareRecord | null;
export function resolveShortcode(shortcode: string): HardwareRecord | null;
export function unicodeFor(id: string): string | null;
export function search(query: string): HardwareRecord[];
export function parents(id: string): string[];
export function children(id: string): HardwareRecord[];
export function relationsFor(id: string): HardwareRelation[];
export function compatibleWith(id: string): HardwareRecord[];
export function connectionsFor(id: string): HardwareRelation[];
""", encoding="utf-8")
    manifest_path = ROOT / "packages/js/package.json"
    manifest_path.write_text(json.dumps({"name": "pcb-otf", "version": project_version(), "description": "Semantic metadata and relationship helpers for PCB.OTF", "main": "index.js", "types": "index.d.ts", "license": "MIT", "sideEffects": False}, indent=2) + "\n", encoding="utf-8")
    (ROOT / "docs/registry.js").write_text(f"window.PCB_REGISTRY = {json.dumps(rows, ensure_ascii=False)};\nwindow.PCB_RELATIONS = {json.dumps(relations, ensure_ascii=False)};\nwindow.PCB_ASSEMBLIES = {json.dumps(scene_data, ensure_ascii=False)};\n", encoding="utf-8")
    category_counts = {}
    for row in rows: category_counts[row["category"]] = category_counts.get(row["category"], 0) + 1
    cps = [int(row["codepoint"][2:], 16) for row in rows]
    stats = {"version": project_version(), "object_count": len(rows), "category_counts": category_counts, "pua": {"first": f"U+{min(cps):04X}", "last": f"U+{max(cps):04X}", "assigned": len(cps)}, "shortcodes": len(rows), "relation_count": len(relations)}
    (ROOT / "unicode-proposal/statistics.json").write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")
    print(f"generated registries and JS metadata for {len(rows)} hardware objects")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
